@startuml
	
	hide circles
	hide methods
	
	class Sortie {
		+ id : int
		+ date : Date
		+ destination : String
		+ distanceTotalAller : double
		+ distanceTotalRetour : double
		+ montantPeageAller : double
		+ montantPeageRetour : double			
	}
	
	class Vehicule {
		+ id : int
		+ carburant : String
		+ vehicule : String
		+ consomation : double
		+ nbPlace : int
		+ commentairess : String
	}
	
	class Personne {
		+ id : int
		+ nom : String
		+ mail : String
		+ login : String
		+ password : String
		+ droit : String
	}
	
	class Payer {
		+payer : boolean
	}
	
	
	
	Sortie "0..*"--"1" Vehicule : Utiliser
	Sortie "0..*"-l-"1..*" Personne : "                 Sortir        "
	(Personne, Sortie) .. Payer
	
	Personne "1"-r-"0..*" Sortie : "      Organiser          "
	Personne "1"--"0..*" Vehicule : "Posseder"
	
	
	
@enduml