@startuml
	
	hide circles
	hide methods
	
	class Sortie {
		+ Id : int
		+ Date : Date
		+ Destination String
		+ Trajet : int
		+ MontantPeage : double
	}
	
	class Vehicule {
		+ Id : int
		+ Carburant : String
		+ Vehicule : String
		+ Consomation : int
	}
	
	class Personne {
		+ Id : int
		+ Nom : String
		+ Role : String
		+ Droit : String
	}
	
	Sortie "0..*"--"1" Vehicule : Utiliser
	Sortie "0..*"--"1..*" Personne : Sortir
	Personne "1"--"1" Sortie : > Organiser
	
@enduml